@startuml Manage Hotel (POST)

footer Page %page% of %lastpage%
title "Manage Hotel (POST)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:hotel" as HotelRouter
participant "<<middleware>>\n:auth" as Middleware
participant "<<controllers>>\n:hotel" as HotelController
participant "<<model>>\n:Hotel" as HotelModel
database "<<MongoDB>>\n:hotel" as HotelDatabase

client->server ++:req.post('/hotels')
server->HotelRouter ++:app.use('/hotels',protect , authorize('admin'),createHotel)
HotelRouter->Middleware ++: protect()
alt if error
Middleware-->client --:response(401)
else
HotelRouter->Middleware ++: authorize('admin')
alt if error
Middleware-->client --:response(401)
else
HotelRouter -> HotelController ++:createHotel()
HotelController->HotelModel ++:create(req.body)
HotelModel ->HotelDatabase ++: HotelSchema
HotelDatabase --> HotelModel --: hotel
HotelController <-- HotelModel --:hotel
HotelController-->client --:response
end
end
@enduml
