@startuml Manage Reservation (GET ONE)

footer Page %page% of %lastpage%
title "Manage Reservation (GET ONE)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:reservation" as ReservationRouter
participant "<<middleware>>\n:auth" as Middleware
participant "<<controllers>>\n:reservation" as ReservationController
participant "<<model>>\n:Reservation" as ReservationModel
database "<<MongoDB>>\n:reservation" as ReservationDatabase

client->server ++:req.get('/reservation/{id}')
server->ReservationRouter ++:app.use('/reservation/{id}', protect,getReservation)
ReservationRouter->Middleware ++: protect()
alt if error
Middleware-->client --:response(401)
else
ReservationRouter -> ReservationController ++:getReservation(req.path.id)
ReservationController->ReservationModel ++:find(hotelId=req.path.id)
ReservationModel ->ReservationDatabase ++: ReservationSchema
ReservationDatabase --> ReservationModel --: reservation
ReservationController <-- ReservationModel --:reservation
alt if (!reservation)
ReservationController-->client :response(404)
else
ReservationController-->client --:response(200)
end
end

@enduml
